from openai import OpenAI
import json, os
import pandas as pd
from datetime import datetime, timedelta
from tqdm import tqdm
from IPython.display import display, Markdown


# @title LLM function

def llm(client, system_prompt, user_prompt, model_name="gpt-4o-mini"):
  try:
      # Craft the messages to pass to chat.completions.create
      prompt = [
          {'role':'system', 'content': system_prompt},
          {'role': 'user', 'content': user_prompt}
      ]

      response = client.chat.completions.create(
          model=model_name,
          messages=prompt,
          temperature=0 # for deterministic output
      )

      return response.choices[0].message.content.strip()

  except Exception as e:
      prediction = f'Sorry, I encountered the following error: \n {e}'
      print(prediction)

# Data loading function using pandas to read the CSV file and clean the data 
def load_data(file_path):
    try:
        print(f"Loading data from {file_path}...")
        df = pd.read_csv(file_path, index_col="email_id", encoding='latin-1')
        # df = pd.read_csv("/content/Alex_emails_march_04.csv", index_col="email_id", encoding='latin-1') 
        print(f"Data loaded successfully. Number of records: {len(df)}")
         # Filter and save rows that are from one day previous to March 4, 2025 (i.e., March 3, 2025)
        yesterday_date = pd.to_datetime("3/3/2025").strftime('%m/%d/%Y')
        df['date_received'] = pd.to_datetime(df['date_received']).dt.strftime('%m/%d/%Y')

        yesterday_emails = df[df['date_received'] == yesterday_date].reset_index(drop=True)
        print(f"Filtered Emails Count: {len(yesterday_emails)}")
        #yesterday_emails.to_csv("yesterday_emails.csv", index=False)  # Save to a new CSV file
        return yesterday_emails
    
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

def task0_categorize_emails(client, yesterday_emails):
    """
    Task: Categorize the emails from yesterday into six categories using the LLM.
    """
    categories = ['Urgent & High-Priority Emails',
              'Deadline-Driven Emails',
              'Routine Updates & Check-ins',
              'Non-Urgent Informational Emails',
              'Personal & Social Emails',
              'Spam/Unimportant Emails']

    if yesterday_emails is None:
        return

    # Define system prompt
    system_prompt = (
        "You are an AI email assistant. Your task is to classify the yesterbox emails into the following categories: " \
        "Urgent & High-Priority Emails(need immediate attention), " \
        "Deadline-Driven Emails (time-sensitive emails or meeting requests that need attention today or by given deadline date), " \
        "Routine Updates & Check-ins (require review and acknowledgment without immediate action), " \
        "Non-Urgent Informational Emails (informational emails, can be deferred or delegated to another time or person), " \
        "Personal & Social Emails (can be reviewed optionally at a later time), " \
        "Spam/Unimportant Emails (unwanted or unsolicited messages). " \
        "Note that your response should include only one of the above six categories and nothing else. " \
        "Example Email : 'You Won a Free iPhone 15 Pro! ?? Click to Claim'" \
            "Expected Response : 'Spam/Unimportant Emails'"
    )

    # Iterate through each inquiry and generate a response
    '''
    for index, row in df.iterrows():
        user_prompt = f"Email received: {row['body']}\nClassify this email into one of the six categories mentioned in the system prompt."
        response = llm(client, system_prompt, user_prompt)
        print(f"Email: {row['body']}\nCategory: {response}\n{'-'*50}")
    '''
    
    if 'category' not in yesterday_emails.columns:
        yesterday_emails['category'] = None  # Create the column if it does not exist

    for index, row in tqdm(yesterday_emails.iterrows(), total=yesterday_emails.shape[0], desc='Processing emails'):
        #print(row.to_string())
        user_prompt = "Classify this email into one of the six categories mentioned in the system prompt."
        prompt = f"""{user_prompt}
            Please find the attached email below from yesterday that need to be analyzed:
            ```
            {row.to_string()}
            ```
        """
        category_by_llm = llm(client,system_prompt, prompt)

        # Append the category generated by the LLM to the 'category' column in the same row
        if category_by_llm in categories:
            yesterday_emails.at[index, 'category'] = category_by_llm
        else:
            yesterday_emails.at[index, 'category'] = ""

    yesterday_emails.to_csv("yesterday_emails_with_categories.csv", index=False)  # Save the updated DataFrame to a new CSV file
    return yesterday_emails


def task11_summary_dashboard(client, yesterday_emails_with_categories):
    """
    Task 1.1: Generate a summary dashboard of the categorized emails.
    """
    print("Generating Summary Dashboard...")
    categories = ['Urgent & High-Priority Emails',
            'Deadline-Driven Emails',
            'Routine Updates & Check-ins',
            'Non-Urgent Informational Emails',
            'Personal & Social Emails',
            'Spam/Unimportant Emails']
    if yesterday_emails_with_categories is None:
        return

    # Define system prompt
    system_prompt = (
        f"You are an AI Email Assistant that is excellent at producing executive summaries of the emails received."\
        "Your tasks are: " \
        "1. Read the CSV-formatted email data" \
        "2. Count the number of emails in each of the six categories: {categories} using values in the CSV column named 'category'" \
        "3. Produce an executive summary output with numbered sections as described in the detailed instructions below." \
        "4. Ensure the output is clear, concise, and formatted for easy reading." \
        "Generate executive summary output strictly in the format below:" \
        "## Executive Summary of Emails" \
        "1. **   Total Number of Emails Received:**(Insert total number of emails)" \
        "2. **Total Number of Emails from Yesterday:** (Insert total number of emails received yesterday)" \
        "   (consider today's date as March 4, 2025)" \
        "3. **Email Breakdown by Category (Count Only):**"\
            "* **Urgent & High Priority Emails:**[Insert total number of emails in {categories[0]}]"\
            "* **Deadline-Driven Emails:**[Insert total number of emails in {categories[1]}]"\
            "* **Routine Updates (Review & Acknowledge):** [Insert total number of emails in {categories[2]}]"\
            "* **Non-Urgent Informational Emails:** [Insert total number of emails in {categories[3]}]" \
            "* **Personal & Social Emails:** [Insert total number of emails in {categories[4]}]" \
            "* **Spam/Unimportant Emails:** [Insert total number of emails in {categories[5]}]" \
        "4. ** AI Conclusion:**"\
            "* **Critical Emails Requiring Immediate Attention:**"\
                "* **Urgent & High Priority Emails:**[Insert total number of emails in {categories[0]}]"\
                "* **Deadline-Driven Emails:**[Insert total number of emails in {categories[1]}]"\
                "* **Total Critical Emails:**[Sum of Urgent & High-priority Email count and Deadline-driven Email count]"\
            "* **Emails That Can Be Reviewed Later:**"\
                "* **Routine Updates:**[Insert total number of emails in {categories[2]}]"\
                "* **Non-Urgent Informational Emails:**[Insert total number of emails in {categories[3]}]"\
                "* **Personal & Social Emails:** [Insert total number of emails in {categories[4]}]"\
                "* **Spam/Unimportant Emails:** [Insert total number of emails in {categories[5]}]"\
                "* **Total Non-Critical Emails:**[Sum of Routine Update count, Non-urgent Email count, Personal Email count and Spam Email count]"\
        "#### Summary Insights"\
        "[Brief paragraph summarizing the overall email situation for the day based on the counts provided, highlighting how many emails require immediate attention and how many could be addressed later. Comment on the workload and suggest any prioritization if necessary.]" 
    )
    
    user_prompt = "Read the email data and generate the executive summary dashboard as described in the system prompt."
    prompt = f"""{user_prompt}
        Please use the filtered email data below to perform analysis and summarization:
        ```
        {yesterday_emails_with_categories.to_string()}
        ```
    """
    response = llm(client,system_prompt, prompt)
    print(f"Summary Dashboard Generated:\n {response}")
    #display(Markdown(response))

# main function to call the LLM, data loading function and generate email responses
# execute this function to run the program
def main():

    model_name = "gpt-4o-mini"
    print(f"Using model: {model_name}")

    # Load the JSON file and extract values
    file_name = 'Week 9 - Project/config.json'
    with open(file_name, 'r') as file:
        config = json.load(file)
        os.environ['OPENAI_API_KEY']  = config.get("API_KEY") # Loading the API Key
        os.environ["OPENAI_BASE_URL"] = config.get("OPENAI_API_BASE") # Loading the API Base Url
    
    client = OpenAI()

    # Load the data
    data_file = 'Week 9 - Project/Alex_emails_march_04.csv'  # Ensure this file exists in the same directory
    yesterday_emails = load_data(data_file)
    print(yesterday_emails.head())

    yesterday_emails_with_categories = task0_categorize_emails(client, yesterday_emails)
    task11_summary_dashboard(client, yesterday_emails_with_categories)
    

if __name__ == "__main__":
    print("Starting AI Email Assistant...")
    main()